### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mzerres** [ol0lll/ckeditor_iframe#1]
After installing the module I get the following error on edit text format settings:

> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "dialog" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (Zeile 52 in /Users/markuszerres/Documents/Jobs/Websites/tvw-neu/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

**Comment by ol0lll** [comment]
Hi,

sorry this is not clear from the README, you have to install ckeditor_dialog and ckeditor_fakeobjects for this to work.

**Comment by mzerres** [comment]
Now it works like a charme. Thanks, you helped me a lot.
